import Colores from '../../../../assets/colors/colores';
import {StyleSheet} from 'react-native';

const estilosHome = StyleSheet.create({
  contenedor: {
    flex: 1,
    backgroundColor: Colores.fondo,
    paddingTop: 10,
  },
  seccion: {
    marginBottom: 24,
    paddingLeft: 16,
    paddingVertical: 16,
    paddingTop: 6,
    marginTop: 30, 
    marginHorizontal: 10,
    borderWidth: 4,
    borderColor: Colores.grisOscuro,
  },
  tituloSeccion: {
    backgroundColor: Colores.purpura,
    color: 'white',
    fontSize: 10,
    fontFamily: 'PressStart2P',
    alignSelf: 'flex-start',
    paddingHorizontal: 10,
    paddingVertical: 4,
    marginBottom: 10,
    borderColor: Colores.purpuraClaro,
    borderWidth: 2,
    marginTop:-18,
  },
  tarjeta: {
    width: 140,
    marginRight: 12,
    padding: 8,
    borderWidth: 2,
    borderTopWidth: 2,
    borderLeftWidth: 2,
    borderRightWidth: 2,
    borderBottomWidth: 2,
    borderTopColor: Colores.purpuraOscuro,
    borderLeftColor: Colores.purpuraOscuro,
    borderRightColor: Colores.purpuraClaro,
    borderBottomColor: Colores.purpuraClaro,
  },
  contenedorImagen: {
    position: 'relative',
    width: '100%',
    height: 200,
    marginBottom: 8,
  },
  imagen: {
    width: '111%',           
    height: 180,
    marginBottom: 6,
    marginLeft: -6,
    marginTop:-6,
    justifyContent: 'center',
    backgroundColor:Colores.gris,
  },
    overlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: 'center',
    alignItems: 'center',
  },
    textoImagen: {
    color: 'black',
    fontFamily: 'PressStart2P',
    fontSize: 7,
    textAlign: 'center',
    marginTop:-20,
  },
  titulo: {
    fontFamily: 'PressStart2P',
    fontSize: 9,
    color: 'white',
    marginBottom: 3,
    marginTop:-20
  },
  generos: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginTop:1,
  },
  genero: {
    fontSize: 10,
    color: 'white',
    marginRight: 4,
    backgroundColor: Colores.grisOscuro,
    paddingHorizontal: 4,
    marginBottom: 2,
    padding:5,
  },
});
export default estilosHome;